#!/bin/bash
xsltproc --xinclude ~/mathbook/xsl/mathbook-latex.xsl ./aam-index.xml > AAM.tex
rm ../latex/AAM.*
mv AAM.tex ../latex/
cd ../latex
latexmk -lualatex -gg -bibtex -synctex=1 AAM.tex
cd ../xml
